server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment-route1  #路由id
          uri: lb://CLOUD-PAYMENT-SERVICE  #匹配后提供路由服务的地址
#          filters:
#            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id值为1024
          predicates:
            - Path=/payment/**  #断言，路径匹配的进行路由
#            - After=2022-08-06T11:01:20.156+08:00[Asia/Shanghai]  #在此时间之后才能访问
#            - Before=2022-09-05T15:10:03.685+08:00[Asia/Shanghai] #在此时间之前才能访问
#            - Between=2020-02-02T17:45:06.206+08:00[Asia/Shanghai],2020-03-25T18:59:06.206+08:00[Asia/Shanghai] #在此时间之间才能访问
#            - Cookie=username,zzyy #cookie中带有此键值才能访问
#            - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Host=**.atguigu.com #host的值匹配此才能访问
#            - Method=GET #该请求方式才能被访问
#            - Query=username, \d+  # 要有参数名username并且值还要是整数才能路由




eureka:
  instance:
    instance-id: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
